### ISSUE TITLE
Wrong Autofill for Article Collection: Undesired Color and Wrong Font

### ISSUE THREAD

**Issue by tpreusse** [orbiting/publikator-frontend#180]
## Bug Report

bei der Artikelsammlung übernimmt es die Ameisenfarbe (ausser beim Autor) von hand kann ich es nicht ändern, könnt ir das mal anschauen?

ist es möglich, dass Ameisen in der Artikelvorschau nicht als Ameisen angezeigt werden (also mit der korrekten Titelschrift)?

**Steps to Reproduce**

<img width="984" alt="screen shot 2018-11-16 at 10 25 44" src="https://user-images.githubusercontent.com/410211/48612702-0432d900-e98a-11e8-9b5e-82115504c88d.png">

- Artikelsammlung machen
- Vom Artikel übernehmen
- Ameise auswählen

[Version mit roter Frabe im Publikator](https://publikator.republik.ch/repo/republik/article-klimareport/edit?commitId=0bb8ac3785dec38ae522a685d5bf59e759091ca6)

**Actual Results**

Rote Schrift. Editorial Font.

**Expected Results**

Schwarze Schrift. Scribble Font.

**Comment by uxengine** [comment]
Fixed.

<img width="966" alt="screenshot 2018-11-26 at 18 53 58" src="https://user-images.githubusercontent.com/23520051/49032397-ae8dd600-f1ac-11e8-8d26-cf04b8585c69.png">
