### ISSUE TITLE
Source code view drops publishDate query param

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/publikator-frontend#259]
## Bug Report

**Steps to Reproduce**

1. Open calender view
2. Click "create" («Erstellen») on a placeholder entity
3. Click "edit source code" («Quellcode bearbeiten»)
4. Click "apply" («Übernehmen»)
5. Click "commit"

**Actual Results**

Repository is created as intended, however publish date is not set.

**Expected Results**

Repository is created and publish date is set.

**Possible Solutions**

Query param `publishDate` is dropped while switch to source code view.

**Comment by tpreusse** [comment]
I once had a similar issue I never managed to report: creating a new article via and pasting ended up creating a template instead of a regular article. Maybe also a query param not transported in source view?

**Comment by annatraussnig** [comment]
yes – I would believe so. Fixing asap.
