### ISSUE TITLE
Darkmode: Block quote wrong in preview

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/publikator-frontend#296]
## Bug Report

Block quote compontent in preview is renderd w/ wrong font color when dark mode is toggled on.

(Once published, in production, block quote is rendered as expected.)

**Actual Results**

<img width="785" alt="Bildschirmfoto 2021-08-27 um 14 05 35" src="https://user-images.githubusercontent.com/331800/131125160-0e91fb03-5b93-4420-b996-bab32f36e626.png">

**Expected Results**

<img width="754" alt="Bildschirmfoto 2021-08-27 um 14 04 23" src="https://user-images.githubusercontent.com/331800/131125189-1c6a2ffa-aee1-4357-89fe-1466b133eae7.png">

**Comment by patrickvenetz** [comment]
Pub-Doc: https://publikator.republik.ch/repo/republik/article-new-york-city-in-the-1980ies/tree

**Comment by trm217** [comment]
This issue will be solved by a fix in the stylguide.
