### ISSUE TITLE
module/document cleanup

### ISSUE THREAD

**Issue by lukasbuenger** [orbiting/publikator-frontend#66]
- [ ] Remove hard-coded newsletter restrictions from global document module
- [ ] Externalize hard-coded default document structure
- [ ] Formulate a pluggable process to to enforce and normalize meta data

**Comment by tpreusse** [comment]
FYI: I started to re-work `documentPlain` to be a bit more generic:
https://github.com/orbiting/publikator-frontend/pull/64/files#diff-5c81ea87909537b3cafa54a821190ba9

I was thinking of something like this becoming the default document and having the old one become `documentCover`.

I agree with the goals. Not sure how easy it is to make all of it generic.

**Comment by lukasbuenger** [comment]
> Not sure how easy it is to make all of it generic.

Regarding the default document structure, I want to achieve quite the opposite. Modules, the way I see it, offer kind of generic solutions to common problems. And our current document types already have profoundly different requirements in terms of meta, content restrictions and ui. 
But I'll have to give this some more thought.
